# Generated by Django 4.1.7 on 2023-03-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_options_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-salary'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
