# Generated by Django 4.1.7 on 2023-03-25 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vacancy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-salary'], 'verbose_name': 'Vacancy', 'verbose_name_plural': 'Vacancies'},
        ),
    ]
